services:
  _defaults:
    autowire: true
    autoconfigure: true
    
  FRZB\Component\Cryptography\Helper\Random: ~
  
  FRZB\Component\Cryptography\Factory\CryptoFactory:
    arguments:
      - '@FRZB\Component\Cryptography\Helper\Random'
    
  frzb.crypto_service.aes:
    class: phpseclib\Crypt\AES
    factory: ['@FRZB\Component\Cryptography\Factory\CryptoFactoryInterface', 'createAES']
    arguments:
      - '%env(FRZB_CRYPTOGRAPHY_IV)%'
      - '%env(FRZB_CRYPTOGRAPHY_KEY)%'

  FRZB\Component\Cryptography\Service\CryptographyService:
    arguments:
      - '@frzb.crypto_service.aes'
  
  FRZB\Component\Cryptography\Service\CryptographyInterface: '@FRZB\Component\Cryptography\Service\CryptographyService'
  FRZB\Component\Cryptography\Service\DecryptInterface: '@FRZB\Component\Cryptography\Service\CryptographyService'
  FRZB\Component\Cryptography\Service\EncryptInterface: '@FRZB\Component\Cryptography\Service\CryptographyService'
  FRZB\Component\Cryptography\Factory\CryptoFactoryInterface: '@FRZB\Component\Cryptography\Factory\CryptoFactory'
